[package]
name = "factura-rapida"
version = "0.1.4"
description = "SOLRAK para Windows"
authors = ["SOLRAK"]
edition = "2021"

[build-dependencies]
tauri-build = { version = "2.6.3", features = [] }

[dependencies]
serde = { version = "1", features = ["derive"] }
tauri = { version = "2.11.3", features = [] }
tauri-plugin-updater = "2"
url = "2"
serialport = { version = "4", default-features = false }

[features]
default = ["custom-protocol"]
custom-protocol = ["tauri/custom-protocol"]
